// CSharp-React/react-app/src/components/WeatherComponent.js
import React, { useState} from 'react';
import WeatherService from '../services/WeatherService';

function WeatherComponent() {
    const [zipcode, setZipcode] = useState('');
    const [weather, setWeather] = useState({
        lat: '',
        lon: '',
        name: '',
        temp: '',
        feelsLike: '',
        description: '',
        image: '',
    });

    async function getWeather(e) {
        e.preventDefault();
        try {
            const data = await WeatherService.getWeather(zipcode);;
            setWeather({
                lat: data.coord.lat,
                lon: data.coord.lon,
                name: data.name,
                temp: data.main.temp,
                feelsLike: data.main.feels_like,
                description: data.weather[0].description,
                image: `https://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`,
            });
        } catch (error) {
            console.error('An error occurred: ', error);
        }
    }

    return (
        <div>
            <form onSubmit={getWeather}>
                <label>Enter Zipcode: </label>
                <input className="form" type="text" value={zipcode} onChange={(e) => setZipcode(e.target.value)} />
                <input type="submit" className="form" value="Get Weather" />
            </form>
            <div className="output">
                {weather.lat && (
                    <div>
                        You are in {weather.name}.  Your latitude is {weather.lat} and your longitude is {weather.lon}.
                    </div>
                )}
                {weather.temp && (
                    <div>
                        Today's temp is {weather.temp} and it feels like {weather.feelsLike}. {weather.description}
                        <div>
                            <img src={weather.image} alt="Weather icon" />
                        </div>
                    </div>
                )}
            </div>

        </div>
    );
}

export default WeatherComponent;

// Java-Vue/vue/src/components/WeatherComponent.vue
<template>
  <div>
    <form v-on:submit.prevent="getWeather">
      <label>Enter Zipcode: </label>
      <input class="form" type="text" v-model="zipcode" />
      <input type="submit" class="form" value="Get Weather" />
    </form>
    <div class="output">
      <div v-show="lat != ''">
        You are in {{ name }} Your latitude is {{ lat }} and longitude is
        {{ lon }}
      </div>
      <div v-show="temp != ''">
        Today's temp is {{ temp }} and it feel like {{ feelsLike }}

        {{ description }}
        <div>
        <img :src="image" alt="" />
      </div>
      </div>
    </div>
  </div>
</template>
  
  <script>
import service from "../services/WeatherService.js";
export default {
  data() {
    return {
      zipcode: "",
      lat: "",
      lon: "",
      name: "",
      temp: "",
      feelsLike: "",
      description: "",
      id: "",
      icon: "",
      image: "",
    };
  },
  methods: {
    async getWeather() {
      try {
        const response = await service.getWeather(this.zipcode);
        console.log(response.data);
        this.temp = response.data.main.temp;
        this.feelsLike = response.data.main.feels_like;
        this.description = response.data.weather[0].description;
        this.icon = response.data.weather[0].icon;
        this.image =
          "https://openweathermap.org/img/wn/" + this.icon + "@2x.png";
        this.id = response.data.id;
        const createResponse = await service.createWeather(this.zipcode);
        console.log(createResponse.data);
      } catch (error) {
        console.error('An error occured:', error.response || error.message || error);
      }
    },
  },
};
</script>
  
  <style scoped>
output, form{
  display: block;
  margin: 20px;
}
img {
  margin: 20px;
  border: 2px solid black;
  background-color: lightgray;
}
</style>
