// CSharp-React/react-app/src/components/WeatherComponent.js
import React, { useState} from 'react';
import WeatherService from '../services/WeatherService';

function WeatherComponent() {
    const [zipcode, setZipcode] = useState('');
    const [weather, setWeather] = useState({
        lat: '',
        lon: '',
        name: '',
        temp: '',
        feelsLike: '',
        description: '',
        image: '',
    });

    async function getWeather(e) {
        e.preventDefault();
        try {
            const data = await WeatherService.getWeather(zipcode);;
            setWeather({
                lat: data.coord.lat,
                lon: data.coord.lon,
                name: data.name,
                temp: data.main.temp,
                feelsLike: data.main.feels_like,
                description: data.weather[0].description,
                image: `https://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`,
            });
        } catch (error) {
            console.error('An error occurred: ', error);
        }
    }

    return (
        <div>
            <form onSubmit={getWeather}>
                <label>Enter Zipcode: </label>
                <input className="form" type="text" value={zipcode} onChange={(e) => setZipcode(e.target.value)} />
                <input type="submit" className="form" value="Get Weather" />
            </form>
            <div className="output">
                {weather.lat && (
                    <div>
                        You are in {weather.name}.  Your latitude is {weather.lat} and your longitude is {weather.lon}.
                    </div>
                )}
                {weather.temp && (
                    <div>
                        Today's temp is {weather.temp} and it feels like {weather.feelsLike}. {weather.description}
                        <div>
                            <img src={weather.image} alt="Weather icon" />
                        </div>
                    </div>
                )}
            </div>

        </div>
    );
}

export default WeatherComponent;

// Java-Vue/vue/demo/src/components/WeatherComponent.vue
<template>
    <div>
        <form v-on:submit.prevent="getWeather">
            <label for="zip-code">Enter Zip Code:</label>
            <input type="text" id="zip-code" v-model="zipCode" />
            <input type="submit" value="Get Weather" />
        </form>
        
        <div v-show="lat != ''">
            You are in {{ name }}.
            You're latitude is {{ lat }} and your longitude is {{ lon }}.
        </div>

        <div v-show="temp != ''">
            Today's temp is {{ temp }} and it feels like {{ feelsLike }}.
            The weather is {{ description }}.
            <div>
                <img :src="image" />
            </div>
        </div>
    </div>
</template>

<script>
import WeatherService from '../services/WeatherService';

export default {
    data() {
        return {
            zipCode: '',
            lat: '',
            lon: '',
            name: '',
            temp: '',
            feelsLike: '',
            description: '',
            id: '',
            icon: '',
            image: '',
        };
    },

    methods: {
        async getWeather() {
            try {
                const locationResponse = await WeatherService.getLatLon(this.zipCode);
                console.log(locationResponse);
                this.lat = locationResponse.data.lat;
                this.lon = locationResponse.data.lon;
                this.name = locationResponse.data.name;

                const weatherResponse = await WeatherService.getWeather(this.lat, this.lon);
                console.log(weatherResponse);
                this.temp = weatherResponse.data.main.temp;
                this.feelsLike = weatherResponse.data.main.feels_like;
                this.description = weatherResponse.data.weather[0].description;
                this.icon = weatherResponse.data.weather[0].icon;
                this.image = `http://openweathermap.org/img/w/${this.icon}.png`;
                // Process weather data
            } catch (error) {
                console.error(error);
                // Handle error appropriately
            }
        },
    },
}
</script>


<style scoped>

</style>
